---
- name: "www root exist"
  file:
    state: directory
    path: /var/www/blog
- name: "copy MariaDB repo cfg"
  copy:
    src: files/Mariadb.repo
    dest: /etc/yum.repos.d/MariaDB.repo
- name: "install MariaDB"
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - MariaDB-server
      - MariaDB-client
- name: "reload MariaDB"
  systemd:
    name: mariadb
    state: started 
- name: "install mysql related module"
  yum:
    name: "MySQL-python"
    state: present