---
- name: "download and extract wordpress"
  unarchive:
    src: https://pl.wordpress.org/latest-pl_PL.tar.gz
    dest: /var/www
    remote_src: yes
- name: "copy vhost cfg"
  copy:
    src: files/blog-vhost.conf
    dest: /etc/httpd/conf.d/blog.conf
- name: "copy wordpress cfg"
  copy:
    src: files/wp-config.php
    dest: /var/www/wordpress/wp-config.php
- name: "create wordpress's database"
  mysql_db:
    name: "{{DB_NAME}}"
    state: present
- name: "create user && assign privileges"
  mysql_user:
    name: "{{DB_USER}}"
    password: "{{DB_PW}}"
    priv: "{{DB_NAME}}.*:ALL"
    state: present
- name: "reload apache"
  systemd:
    name: httpd
    state: reloaded